chall_root = "example_repo/"
hostname = "bcds.cyberclasscamp.com"

[fly]
org = "amateursctf-2024"
app_name = "amateursctf-2024"

[[caddy.apps.tls.automation.policies]]
[[caddy.apps.tls.automation.policies.issuers]]
module = "acme"
[caddy.apps.tls.automation.policies.issuers.challenges.dns.provider]
name = "cloudflare"
api_token = "7nfQ7tyXaBQL86DXXQUZioDyHOSzrc01Y5m98ysP"
