# this is a challenge toml
name = "go-gopher"
author = "voxal"
description = """
 ...
"""
flag = "amateursCTF{wh0_s@ys_goph3r_i5nt_web?}"

provide = ["main.go", { file = "bot/main.go", as = "bot.go" }]

[containers.main]
build = "."
limits = { cpu = "100m", mem = "100M" }
ports = [7000]

[expose.main]
target = 7000
tcp = 31290

