# this is a challenge toml
name = "go-gopher"
author = "voxal"
description = """wow cool challenge  
...  
okay here is the url {{main.url}}  
and here is another {{tcp.url}}
"""
flag = "amateursCTF{wh0_s@ys_goph3r_i5nt_web?}"

provide = ["challenge.toml"]

[containers.main]
build = "."
limits = { cpu = 1, mem = 256 }
ports = [3000]

[expose.main]
target = 3000
http = "silly-goose"

[expose.tcp]
target = 1111
tcp = 1373



