# this is a challenge toml
name = "go-gopher"
author = "voxal"
description = """
 ...
"""
flag = "amateursCTF{wh0_s@ys_goph3r_i5nt_web?}"

provide = []

[containers.main]
build = "."
limits = { cpu = 1, mem = 256 }
ports = [3000]

[expose.main]
target = 3000
http = "silly-goose"

