name = "BUFFER-OVERFLOW"
author = "unvariant"
description = "default description. contact an admin to write an actual description."
flag = "chal/flag.txt"
provide = []

[containers.chal]
build = "./chal"
ports = [ 5000,]

[expose.chal]
target = 5000
tcp = 1337

[containers.chal.limits]
cpu = 1
mem = 256
